// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // Usar sessionStorage em vez de localStorage para reduzir risco de roubo de token via XSS.
      // O token expira quando o navegador é fechado, aumentando a segurança.
      storage: sessionStorage,
      persistSession: true,
      autoRefreshToken: true,
      // Detectar sessão na URL (necessário para OAuth com Google)
      detectSessionInUrl: true,
    },
  }
);
